### ISSUE TITLE
Risktable doesn't work [Fix included]

### ISSUE THREAD

**Issue by dazim** [visR-sandbox/visR-survival#42]
When I try to add a risktable, I get the following error:

`Error in ggbld$layout$panel_params[[1]]$x$get_labels(): attempt to apply non-function`

Changing line 20 in add_risktable.R to `    if (is.null(time_ticks)) time_ticks <- as.numeric(ggbld$layout$panel_params[[1]]$x.labels)` solves the issue for me.

Could this be something particular to my installation? Since it seemed to work for some of you.

**Comment by SHAESEN2** [comment]
I think this is related to the fact that I forgot to change survfit_object to KM_object in one of the first lines of code.
